routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index');
Route::get('/post/{slug}', 'HomeController@show')->name('post.show');
Route::get('/tag/{slug}', 'HomeController@tag')->name('tag.show');
Route::get('/category/{slug}', 'HomeController@category')->name('category.show');
Route::post('/subscribe', "SubsController@subscribe");
Route::get('/verify/{token}', 'SubsController@verify');




Route::group(['middleware' => 'auth'], function(){
	Route::get('/profile', 'ProfileController@index');
	Route::post('/profile', 'ProfileController@store');
	Route::get('/logout', 'AuthController@logout');
	Route::post('/comment', 'CommentsController@store');
});

Route::group(['middleware' => 'guest'], function(){
	Route::get('/register', 'AuthController@registerForm');
	Route::post('/register', 'AuthController@register');
	Route::get('/login', 'AuthController@loginForm')->name('login');
	Route::post('/login', 'AuthController@login');
});




Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'admin'], function (){
	Route::get('/', 'DashboardController@index');
	Route::resource('/categories', 'CategoriesController');
	Route::resource('/tags', 'TagsController');
	Route::resource('/users', 'UsersController');
	Route::resource('/posts', 'PostsController');
	Route::get('/comments', 'CommentsController@index');
	Route::get('/comments/toggle/{id}', "CommentsController@toggle");
	Route::delete('/comments/{id}/destroy', 'CommentsController@destroy')->name('comment.destroy');
	Route::resource('/subscribers', 'SubscribersController');
});

app/Http/Controllers/SubsController.php
<?php

namespace App\Http\Controllers;

use App\Subscription;
use App\Mail\SubscribeEmail;
use Illuminate\Http\Request;

class SubsController extends Controller
{
    public function subscribe(Request $request) {
    	$this->validate($request, [
    		'email' => 'required|email|unique:subscriptions'
		]);

    	$subs = Subscription::add($request->get('email'));
    	$subs->generateToken();

		\Mail::to($subs)->send(new SubscribeEmail($subs));

    	return redirect()->back()->with('status', 'Проверьте вашу почту!');
	}

	public function verify($token) {
    	$subs = Subscription::where('token', $token)->firstOrFail();
    	$subs->token = null;
    	$subs->save();

    	return redirect('/')->with('status', 'Ваша почта подтверждена!');
	}

}

resources/views/admin/subs/create.blade.php
@extends('admin.layout')

@section('content')
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<section class="content-header">
			<h1>
				Добавить подписчика
				<small>приятные слова..</small>
			</h1>
		</section>

		<!-- Main content -->
		<section class="content">

			<!-- Default box -->
			{{Form::open(['route' => 'subscribers.store'])}}
			<div class="box">
				<div class="box-header with-border">
					<h3 class="box-title">Добавляем подписчика</h3>
					@include('admin.errors')
				</div>
				<div class="box-body">
					<div class="col-md-6">
						<div class="form-group">
							<label for="exampleInputEmail1">Email</label>
							<input type="text" class="form-control" id="exampleInputEmail1" placeholder="" name="email" value="{{old('email')}}">
						</div>
					</div>
				</div>
				<!-- /.box-body -->
				<div class="box-footer">
					<button class="btn btn-success pull-right">Добавить</button>
				</div>
				<!-- /.box-footer-->
			</div>
			{{Form::close()}}
			<!-- /.box -->

		</section>
		<!-- /.content -->
	</div>
@endsection

resources/views/admin/subs/index.blade.php
@extends('admin.layout')

@section('content')
	<div class="content-wrapper">
		<!-- Content Header (Page header) -->
		<section class="content-header">
			<h1>
				Blank page
				<small>it all starts here</small>
			</h1>
			<ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li><a href="#">Examples</a></li>
				<li class="active">Blank page</li>
			</ol>
		</section>

		<!-- Main content -->
		<section class="content">

			<!-- Default box -->
			<div class="box">
				<div class="box-header">
					<h3 class="box-title">Листинг сущности</h3>
				</div>
				<!-- /.box-header -->
				<div class="box-body">
					<div class="form-group">
						<a href="{{route('subscribers.create')}}" class="btn btn-success">Добавить</a>
					</div>
					<table id="example1" class="table table-bordered table-striped">
						<thead>
						<tr>
							<th>ID</th>
							<th>Email</th>
							<th>Действия</th>
						</tr>
						</thead>
						<tbody>
						@foreach($subs as $subscriber)
						<tr>
							<td>{{$subscriber->id}}</td>
							<td>{{$subscriber->email}}
							</td>
							<td></a>
								{{Form::open(['route' => ['subscribers.destroy', $subscriber->id], 'method'=>'delete'])}}
								<button onclick="return confirm('are you sure?')" type="submit" class="delete">
									<i class="fa fa-remove"></i>
								</button>
								{{Form::close()}}
							</td>
						</tr>
						@endforeach
						</tfoot>
					</table>
				</div>
				<!-- /.box-body -->
			</div>
			<!-- /.box -->

		</section>
		<!-- /.content -->
	</div>
@endsection